name: Check pending SQL
on:
  pull_request:

jobs:
  check-pending-sql:
    runs-on: ubuntu-latest
    if: github.repository == 'azerothcore/azerothcore-wotlk'
    steps:
      - uses: actions/checkout@v4
      - name: Check pending SQL
        run: source ./apps/ci/ci-pending.sh
