name: check-codestyle
on:
  pull_request:

jobs:
  check-codestyle:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    if: github.repository == 'azerothcore/azerothcore-wotlk'
    name: check codestyle
    steps:
      - uses: actions/checkout@v4
      - name: Check core codestyle
        run: source ./apps/ci/ci-codestyle.sh
